import type { Component } from 'vue';
import {
  ActivityIcon,
  BatteryIcon,
  BikeIcon,
  BirdIcon,
  Bone01Icon,
  BookOpen01Icon,
  BotIcon,
  BrainIcon,
  BriefcaseBusinessIcon,
  BrushIcon,
  BubbleChatIcon,
  Bug01Icon,
  Building01Icon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  CarIcon,
  CatIcon,
  ChartBarLineIcon,
  ChartCandlestickIcon,
  ChefHatIcon,
  ClapperboardIcon,
  ClockIcon,
  CloudIcon,
  CloudSunRainIcon,
  CodeXmlIcon,
  CoffeeIcon,
  CompassIcon,
  ContactIcon,
  CpuIcon,
  DatabaseIcon,
  DiamondIcon,
  DicesIcon,
  DropletsIcon,
  DumbbellIcon,
  EyeIcon,
  FileTextIcon,
  FilmIcon,
  FingerPrintIcon,
  FishIcon,
  FlagIcon,
  FlameIcon,
  FlaskConicalIcon,
  Flower01Icon,
  GameController01Icon,
  GemIcon,
  GlobeIcon,
  GraduationCapIcon,
  HammerIcon,
  HeadphonesIcon,
  HeartIcon,
  ImageIcon,
  KeyRoundIcon,
  LanguagesIcon,
  Layout01Icon,
  LeafIcon,
  LightbulbIcon,
  ListTodoIcon,
  LockIcon,
  MailIcon,
  MapIcon,
  MapPinIcon,
  MedalIcon,
  MegaphoneIcon,
  MessageCircleIcon,
  MessagesSquareIcon,
  MicIcon,
  MoonIcon,
  MountainIcon,
  Music01Icon,
  NetworkIcon,
  NewspaperIcon,
  NotebookPenIcon,
  PackageIcon,
  PaintBrushIcon,
  PaletteIcon,
  PenLineIcon,
  PenTool01Icon,
  PencilIcon,
  PlaneIcon,
  PlugIcon,
  PresentationIcon,
  PuzzleIcon,
  RabbitIcon,
  RocketIcon,
  ScaleIcon,
  SchoolIcon,
  ScissorsIcon,
  SearchIcon,
  SendIcon,
  ServerIcon,
  SettingsIcon,
  ShapesIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShipIcon,
  ShippingTruck01Icon,
  ShoppingCartIcon,
  SigmaIcon,
  SparklesIcon,
  StethoscopeIcon,
  StickyNoteIcon,
  StoreIcon,
  SunIcon,
  SwordsIcon,
  TargetIcon,
  TimerIcon,
  TrainIcon,
  TreesIcon,
  TrophyIcon,
  TruckIcon,
  UserRoundIcon,
  UsersIcon,
  UtensilsIcon,
  VideoIcon,
  WandSparklesIcon,
  WavesIcon,
  WorkflowIcon,
  WrenchIcon,
  ZapIcon,
} from '@hugeicons/core-free-icons';
import { createHugeIcon } from './hugeIcon';
import type { GuruIconName } from '../../../../packages/shared/src/guru-icons';

export const GURU_ICONS: Record<GuruIconName, Component> = {
  Sparkles: createHugeIcon(SparklesIcon),
  Bot: createHugeIcon(BotIcon),
  MessageSquare: createHugeIcon(BubbleChatIcon),
  BookOpen: createHugeIcon(BookOpen01Icon),
  Lightbulb: createHugeIcon(LightbulbIcon),
  Palette: createHugeIcon(PaletteIcon),
  PenTool: createHugeIcon(PenTool01Icon),
  Image: createHugeIcon(ImageIcon),
  Clapperboard: createHugeIcon(ClapperboardIcon),
  Camera: createHugeIcon(CameraIcon),
  Music2: createHugeIcon(Music01Icon),
  WandSparkles: createHugeIcon(WandSparklesIcon),
  CodeXml: createHugeIcon(CodeXmlIcon),
  Database: createHugeIcon(DatabaseIcon),
  Globe: createHugeIcon(GlobeIcon),
  ChartColumn: createHugeIcon(ChartBarLineIcon),
  GraduationCap: createHugeIcon(GraduationCapIcon),
  BriefcaseBusiness: createHugeIcon(BriefcaseBusinessIcon),
  Cpu: createHugeIcon(CpuIcon),
  Rocket: createHugeIcon(RocketIcon),
  FlaskConical: createHugeIcon(FlaskConicalIcon),
  Shapes: createHugeIcon(ShapesIcon),
  Workflow: createHugeIcon(WorkflowIcon),
  Layout: createHugeIcon(Layout01Icon),
  Server: createHugeIcon(ServerIcon),
  Network: createHugeIcon(NetworkIcon),
  Container: createHugeIcon(ShippingTruck01Icon),
  ShieldCheck: createHugeIcon(ShieldCheckIcon),
  Bug: createHugeIcon(Bug01Icon),
  CandlestickChart: createHugeIcon(ChartCandlestickIcon),
  Scale: createHugeIcon(ScaleIcon),
  FileText: createHugeIcon(FileTextIcon),
  Brain: createHugeIcon(BrainIcon),
  Heart: createHugeIcon(HeartIcon),
  Target: createHugeIcon(TargetIcon),
  Compass: createHugeIcon(CompassIcon),
  Map: createHugeIcon(MapIcon),
  MapPin: createHugeIcon(MapPinIcon),
  Languages: createHugeIcon(LanguagesIcon),
  Search: createHugeIcon(SearchIcon),
  Mic: createHugeIcon(MicIcon),
  Headphones: createHugeIcon(HeadphonesIcon),
  Video: createHugeIcon(VideoIcon),
  Film: createHugeIcon(FilmIcon),
  Brush: createHugeIcon(BrushIcon),
  Paintbrush: createHugeIcon(PaintBrushIcon),
  Pencil: createHugeIcon(PencilIcon),
  PenLine: createHugeIcon(PenLineIcon),
  Scissors: createHugeIcon(ScissorsIcon),
  Gem: createHugeIcon(GemIcon),
  Diamond: createHugeIcon(DiamondIcon),
  Megaphone: createHugeIcon(MegaphoneIcon),
  Newspaper: createHugeIcon(NewspaperIcon),
  Presentation: createHugeIcon(PresentationIcon),
  NotebookPen: createHugeIcon(NotebookPenIcon),
  StickyNote: createHugeIcon(StickyNoteIcon),
  ListTodo: createHugeIcon(ListTodoIcon),
  Calendar: createHugeIcon(CalendarIcon),
  Clock: createHugeIcon(ClockIcon),
  Timer: createHugeIcon(TimerIcon),
  Mail: createHugeIcon(MailIcon),
  Send: createHugeIcon(SendIcon),
  MessageCircle: createHugeIcon(MessageCircleIcon),
  MessagesSquare: createHugeIcon(MessagesSquareIcon),
  Users: createHugeIcon(UsersIcon),
  UserRound: createHugeIcon(UserRoundIcon),
  Contact: createHugeIcon(ContactIcon),
  Building2: createHugeIcon(Building01Icon),
  Store: createHugeIcon(StoreIcon),
  ShoppingCart: createHugeIcon(ShoppingCartIcon),
  Package: createHugeIcon(PackageIcon),
  Truck: createHugeIcon(TruckIcon),
  Plane: createHugeIcon(PlaneIcon),
  Car: createHugeIcon(CarIcon),
  Bike: createHugeIcon(BikeIcon),
  Train: createHugeIcon(TrainIcon),
  Ship: createHugeIcon(ShipIcon),
  Trees: createHugeIcon(TreesIcon),
  Leaf: createHugeIcon(LeafIcon),
  Flower2: createHugeIcon(Flower01Icon),
  Sun: createHugeIcon(SunIcon),
  Moon: createHugeIcon(MoonIcon),
  Cloud: createHugeIcon(CloudIcon),
  CloudSun: createHugeIcon(CloudSunRainIcon),
  Mountain: createHugeIcon(MountainIcon),
  Waves: createHugeIcon(WavesIcon),
  Flame: createHugeIcon(FlameIcon),
  Droplets: createHugeIcon(DropletsIcon),
  Zap: createHugeIcon(ZapIcon),
  Battery: createHugeIcon(BatteryIcon),
  Plug: createHugeIcon(PlugIcon),
  Settings: createHugeIcon(SettingsIcon),
  Wrench: createHugeIcon(WrenchIcon),
  Hammer: createHugeIcon(HammerIcon),
  Puzzle: createHugeIcon(PuzzleIcon),
  Gamepad2: createHugeIcon(GameController01Icon),
  Dices: createHugeIcon(DicesIcon),
  Trophy: createHugeIcon(TrophyIcon),
  Medal: createHugeIcon(MedalIcon),
  Flag: createHugeIcon(FlagIcon),
  Swords: createHugeIcon(SwordsIcon),
  Shield: createHugeIcon(ShieldIcon),
  Lock: createHugeIcon(LockIcon),
  KeyRound: createHugeIcon(KeyRoundIcon),
  Fingerprint: createHugeIcon(FingerPrintIcon),
  Eye: createHugeIcon(EyeIcon),
  Stethoscope: createHugeIcon(StethoscopeIcon),
  Activity: createHugeIcon(ActivityIcon),
  Dumbbell: createHugeIcon(DumbbellIcon),
  Utensils: createHugeIcon(UtensilsIcon),
  Coffee: createHugeIcon(CoffeeIcon),
  ChefHat: createHugeIcon(ChefHatIcon),
  Dog: createHugeIcon(Bone01Icon),
  Cat: createHugeIcon(CatIcon),
  Bird: createHugeIcon(BirdIcon),
  Fish: createHugeIcon(FishIcon),
  Rabbit: createHugeIcon(RabbitIcon),
  School: createHugeIcon(SchoolIcon),
  Calculator: createHugeIcon(CalculatorIcon),
  Sigma: createHugeIcon(SigmaIcon),
};
