import {
  Sparkles, Bot, MessageSquare, BookOpen, Lightbulb, Palette, PenTool,
  Image, Clapperboard, Camera, Music2, WandSparkles, CodeXml, Database,
  Globe, ChartColumn, GraduationCap, BriefcaseBusiness, Cpu, Rocket,
  FlaskConical, Shapes, Workflow, Layout, Server, Network, Container,
  ShieldCheck, Bug, CandlestickChart, Scale, FileText,
  Brain, Heart, Target, Compass, Map, MapPin, Languages,
  Search, Mic, Headphones, Video, Film, Brush, Paintbrush,
  Pencil, PenLine, Scissors, Gem, Diamond, Megaphone, Newspaper,
  Presentation, NotebookPen, StickyNote, ListTodo, Calendar, Clock, Timer,
  Mail, Send, MessageCircle, MessagesSquare, Users, UserRound, Contact,
  Building2, Store, ShoppingCart, Package, Truck, Plane, Car,
  Bike, Train, Ship, Trees, Leaf, Flower2, Sun,
  Moon, Cloud, CloudSun, Mountain, Waves, Flame, Droplets,
  Zap, Battery, Plug, Settings, Wrench, Hammer, Puzzle,
  Gamepad2, Dices, Trophy, Medal, Flag, Swords, Shield,
  Lock, KeyRound, Fingerprint, Eye, Stethoscope, Activity, Dumbbell,
  Utensils, Coffee, ChefHat, Dog, Cat, Bird, Fish,
  Rabbit, School, Calculator, Sigma,
} from 'lucide-vue-next';
import type { GuruIconName } from '../../../../packages/shared/src/guru-icons';

export const GURU_ICONS = {
  Sparkles, Bot, MessageSquare, BookOpen, Lightbulb, Palette, PenTool,
  Image, Clapperboard, Camera, Music2, WandSparkles, CodeXml, Database,
  Globe, ChartColumn, GraduationCap, BriefcaseBusiness, Cpu, Rocket,
  FlaskConical, Shapes, Workflow, Layout, Server, Network, Container,
  ShieldCheck, Bug, CandlestickChart, Scale, FileText,
  Brain, Heart, Target, Compass, Map, MapPin, Languages,
  Search, Mic, Headphones, Video, Film, Brush, Paintbrush,
  Pencil, PenLine, Scissors, Gem, Diamond, Megaphone, Newspaper,
  Presentation, NotebookPen, StickyNote, ListTodo, Calendar, Clock, Timer,
  Mail, Send, MessageCircle, MessagesSquare, Users, UserRound, Contact,
  Building2, Store, ShoppingCart, Package, Truck, Plane, Car,
  Bike, Train, Ship, Trees, Leaf, Flower2, Sun,
  Moon, Cloud, CloudSun, Mountain, Waves, Flame, Droplets,
  Zap, Battery, Plug, Settings, Wrench, Hammer, Puzzle,
  Gamepad2, Dices, Trophy, Medal, Flag, Swords, Shield,
  Lock, KeyRound, Fingerprint, Eye, Stethoscope, Activity, Dumbbell,
  Utensils, Coffee, ChefHat, Dog, Cat, Bird, Fish,
  Rabbit, School, Calculator, Sigma,
} satisfies Record<GuruIconName, typeof Sparkles>;
